#pragma once

#define WIDTH_OF_ROOM 15
#define HEIGHT_OF_ROOM 9

#define SIZE_OF_A_TILE 16

#define GOLD_NUMBER 1.618033988749894

#define WINDOW_WIDTH 2*GOLD_NUMBER*SIZE_OF_A_TILE*WIDTH_OF_ROOM
#define WINDOW_HEIGHT 2*GOLD_NUMBER*SIZE_OF_A_TILE*HEIGHT_OF_ROOM

#define FRAME_PER_SECOND 60
